#cloud-config
packages:
  - lvm2

disk_setup:
%{ for disk in extra_disk ~}
  /dev/sd${disk.disk_letter}:
    table_type: gpt
    layout: true
    overwrite: true
%{ endfor ~}

lvm:
%{ for disk in extra_disk ~}
  ${disk.vg}:
    devices: ["/dev/sd${disk.disk_letter}1"]
%{ endfor ~}

fs_setup:
%{ for disk in extra_disk ~}
  - label: ${disk.lv}
    filesystem: ext4
    device: /dev/${disk.vg}/${disk.lv}
    overwrite: true
%{ endfor ~}

mounts:
%{ for disk in extra_disk ~}
  - [ /dev/${disk.vg}/${disk.lv}, ${disk.mount} ]
%{ endfor ~}
runcmd:
  - [ sh, -c, "echo 'Cloud-init started' >> /var/log/cloud-init-debug.log" ]
