#cloud-config
packages:
  - lvm2

runcmd:
  - [ bash, -c, |
      sleep 5 &&
      parted /dev/sdb --script mklabel gpt mkpart primary ext4 0% 100% &&
      pvcreate /dev/sdb1 &&
      vgcreate vg_data /dev/sdb1 &&
      lvcreate -l 100%FREE -n lv_data vg_data &&
      mkfs.ext4 /dev/vg_data/lv_data &&
      mkdir -p /data &&
      echo '/dev/vg_data/lv_data /data ext4 defaults 0 0' >> /etc/fstab &&
      mount /data
    ]

