#cloud-config
packages:
  - lvm2

runcmd:

  %{ if extend_lvm ~}
  - parted /dev/sda --script resizepart 2 {{ disk }}GB
  - sleep 5
  - pvresize /dev/sda3
  - lvextend -l +100%FREE /dev/{{ extend_lvm.vg }}/{{ extend_lvm.lv }}
  - resize2fs /dev/{{ extend_lvm.vg }}/{{ extend_lvm.lv }}
  - [ sh, -c, "echo '/dev/{{ extend_lvm.vg }}/{{ extend_lvm.lv }} {{ extend_lvm.mount }} ext4 defaults 0 0' >> /etc/fstab" ]
  - mount {{ extend_lvm.mount }}
  - [ sh, -c, "echo 'Cloud-init finished LV extension' >> /var/log/cloud-init-debug.log" ]
  %{ endif ~}

%{ for disk in extra_disk ~}
  - parted /dev/sd${disk.disk_letter} --script mklabel gpt mkpart primary ext4 0% 100%
  - sleep 2
  - pvcreate /dev/sd${disk.disk_letter}1
  - vgcreate ${disk.vg} /dev/sd${disk.disk_letter}1
  - lvcreate -l 100%FREE -n ${disk.lv} ${disk.vg}
  - mkfs.ext4 /dev/${disk.vg}/${disk.lv}
  - mkdir -p ${disk.mount}
  - mount /dev/${disk.vg}/${disk.lv} ${disk.mount}
  - grep "/dev/${disk.vg}/${disk.lv}" /etc/fstab || echo "/dev/${disk.vg}/${disk.lv} ${disk.mount} ext4 defaults 0 0" >> /etc/fstab
%{ endfor ~}

  - [ sh, -c, "echo 'Cloud-init finished LVM setup' >> /var/log/cloud-init-debug.log" ]

