#cloud-config
packages:
  - lvm2

runcmd:
  - echo "=== Start cloud-init disk setup debug ===" | tee /var/log/cloud-init-debug.log
  - parted /dev/sdb --script mklabel gpt mkpart primary ext4 0% 100% 2>&1 | tee -a /var/log/cloud-init-debug.log
  - sleep 5
  - pvcreate /dev/sdb1 2>&1 | tee -a /var/log/cloud-init-debug.log
  - vgcreate ${vg} /dev/sdb1 2>&1 | tee -a /var/log/cloud-init-debug.log
  - lvcreate -L 100%FREE -n ${lv} ${vg} 2>&1 | tee -a /var/log/cloud-init-debug.log
  - mkfs.ext4 /dev/${vg}/${lv} 2>&1 | tee -a /var/log/cloud-init-debug.log
  - mkdir -p ${mount} 2>&1 | tee -a /var/log/cloud-init-debug.log
  - mount /dev/${vg}/${lv} ${mount} 2>&1 | tee -a /var/log/cloud-init-debug.log
  - bash -c "echo '/dev/${vg}/${lv} ${mount} ext4 defaults 0 0' >> /etc/fstab" 2>&1 | tee -a /var/log/cloud-init-debug.log
  - echo "=== End cloud-init disk setup debug ===" | tee -a /var/log/cloud-init-debug.log
