#cloud-config
packages:
  - lvm2

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: true

lvm:
  ${vg}:
    devices:
      - /dev/sdb1

fs_setup:
  - device: /dev/mapper/${vg}-${lv}
    filesystem: ext4
    label: ${lv}
    overwrite: false

mounts:
  - ["/dev/mapper/${vg}-${lv}", "${mount}", "ext4", "defaults,nofail", "0", "2"]
