#cloud-config
packages:
  - lvm2

runcmd:
  - parted /dev/sdb --script mklabel gpt mkpart primary ext4 0% 100%
  - sleep 5
  - pvcreate /dev/sdb1
  - vgcreate ${vg} /dev/sdb1
  - lvcreate -L 100%FREE -n ${lv} ${vg}
  - mkfs.ext4 /dev/${vg}/${lv}
  - mkdir -p ${mount}
  - mount /dev/${vg}/${lv} ${mount}
  - echo '/dev/${vg}/${lv} ${mount} ext4 defaults 0 0' >> /etc/fstab
